//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 02:41:26 AM BST 
//


package eu.aniketos;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for declType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="declType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{}typeType"/>
 *         &lt;element name="identifier" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="value">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{}expType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "declType", propOrder = {
    "type",
    "identifier",
    "value"
})
public class DeclType {

    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected String identifier;
    @XmlElement(required = true)
    protected DeclType.Value value;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the identifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIdentifier() {
        return identifier;
    }

    /**
     * Sets the value of the identifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIdentifier(String value) {
        this.identifier = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link DeclType.Value }
     *     
     */
    public DeclType.Value getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeclType.Value }
     *     
     */
    public void setValue(DeclType.Value value) {
        this.value = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{}expType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "expType"
    })
    public static class Value {

        @XmlElementRefs({
            @XmlElementRef(name = "lessthan", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "equal", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "not", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "morequalthan", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "notequal", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "and", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "iconst", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dif", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "sconst", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "append", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "mod", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "or", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "lessequalthan", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "bconst", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "invocation", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "sum", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "morethan", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "identifier", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "mul", type = JAXBElement.class, required = false)
        })
        protected JAXBElement<?> expType;

        /**
         * Gets the value of the expType property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Unary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
         *     {@link JAXBElement }{@code <}{@link InvocationType }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     
         */
        public JAXBElement<?> getExpType() {
            return expType;
        }

        /**
         * Sets the value of the expType property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Unary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
         *     {@link JAXBElement }{@code <}{@link InvocationType }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     
         */
        public void setExpType(JAXBElement<?> value) {
            this.expType = value;
        }

    }

}
