//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 02:41:26 AM BST 
//


package eu.aniketos;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for reactionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="reactionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="guard">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;group ref="{}expType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="update" type="{}updateType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "reactionType", propOrder = {
    "guard",
    "update"
})
public class ReactionType {

    @XmlElement(required = true)
    protected ReactionType.Guard guard;
    @XmlElement(required = true)
    protected UpdateType update;

    /**
     * Gets the value of the guard property.
     * 
     * @return
     *     possible object is
     *     {@link ReactionType.Guard }
     *     
     */
    public ReactionType.Guard getGuard() {
        return guard;
    }

    /**
     * Sets the value of the guard property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReactionType.Guard }
     *     
     */
    public void setGuard(ReactionType.Guard value) {
        this.guard = value;
    }

    /**
     * Gets the value of the update property.
     * 
     * @return
     *     possible object is
     *     {@link UpdateType }
     *     
     */
    public UpdateType getUpdate() {
        return update;
    }

    /**
     * Sets the value of the update property.
     * 
     * @param value
     *     allowed object is
     *     {@link UpdateType }
     *     
     */
    public void setUpdate(UpdateType value) {
        this.update = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;group ref="{}expType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "expType"
    })
    public static class Guard {

        @XmlElementRefs({
            @XmlElementRef(name = "sconst", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "not", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "dif", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "sum", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "append", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "or", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "and", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "identifier", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "equal", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "mod", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "iconst", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "invocation", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "morethan", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "bconst", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "mul", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "lessthan", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "morequalthan", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "notequal", type = JAXBElement.class, required = false),
            @XmlElementRef(name = "lessequalthan", type = JAXBElement.class, required = false)
        })
        protected JAXBElement<?> expType;

        /**
         * Gets the value of the expType property.
         * 
         * @return
         *     possible object is
         *     {@link JAXBElement }{@code <}{@link Unary }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link InvocationType }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     
         */
        public JAXBElement<?> getExpType() {
            return expType;
        }

        /**
         * Sets the value of the expType property.
         * 
         * @param value
         *     allowed object is
         *     {@link JAXBElement }{@code <}{@link Unary }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link String }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link InvocationType }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Boolean }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     {@link JAXBElement }{@code <}{@link Binary }{@code >}
         *     
         */
        public void setExpType(JAXBElement<?> value) {
            this.expType = value;
        }

    }

}
