//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.03 at 02:41:26 AM BST 
//


package eu.aniketos;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ruleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ruleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="before" type="{}whenType"/>
 *           &lt;element name="after" type="{}afterType"/>
 *           &lt;element name="exceptional" type="{}whenType"/>
 *         &lt;/choice>
 *         &lt;element name="perform" type="{}performType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ruleType", propOrder = {
    "beforeOrAfterOrExceptional",
    "perform"
})
public class RuleType {

    @XmlElementRefs({
        @XmlElementRef(name = "exceptional", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "after", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "before", type = JAXBElement.class, required = false)
    })
    protected JAXBElement<? extends WhenType> beforeOrAfterOrExceptional;
    @XmlElement(required = true)
    protected PerformType perform;

    /**
     * Gets the value of the beforeOrAfterOrExceptional property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link WhenType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AfterType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WhenType }{@code >}
     *     
     */
    public JAXBElement<? extends WhenType> getBeforeOrAfterOrExceptional() {
        return beforeOrAfterOrExceptional;
    }

    /**
     * Sets the value of the beforeOrAfterOrExceptional property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link WhenType }{@code >}
     *     {@link JAXBElement }{@code <}{@link AfterType }{@code >}
     *     {@link JAXBElement }{@code <}{@link WhenType }{@code >}
     *     
     */
    public void setBeforeOrAfterOrExceptional(JAXBElement<? extends WhenType> value) {
        this.beforeOrAfterOrExceptional = value;
    }

    /**
     * Gets the value of the perform property.
     * 
     * @return
     *     possible object is
     *     {@link PerformType }
     *     
     */
    public PerformType getPerform() {
        return perform;
    }

    /**
     * Sets the value of the perform property.
     * 
     * @param value
     *     allowed object is
     *     {@link PerformType }
     *     
     */
    public void setPerform(PerformType value) {
        this.perform = value;
    }

}
